package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CardPlaceholderRefresh: ImageVector
    get() {
        if (_CardPlaceholderRefresh != null) {
            return _CardPlaceholderRefresh!!
        }
        _CardPlaceholderRefresh = ImageVector.Builder(
            name = "CardPlaceholderRefresh",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _CardPlaceholderRefresh!!
    }

@Suppress("ObjectPropertyName")
private var _CardPlaceholderRefresh: ImageVector? = null
