package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CardBack: ImageVector
    get() {
        if (_CardBack != null) {
            return _CardBack!!
        }
        _CardBack = ImageVector.Builder(
            name = "CardBack",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 0.5f)
                horizontalLineToRelative(13f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(14f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 2.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(4f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(3f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(7f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFDCD8D1)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(5f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 46.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFDCD9D1)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFDCD8D0)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(6f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFDDD8D1)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _CardBack!!
    }

@Suppress("ObjectPropertyName")
private var _CardBack: ImageVector? = null
