package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ClubsUnknown: ImageVector
    get() {
        if (_ClubsUnknown != null) {
            return _ClubsUnknown!!
        }
        _ClubsUnknown = ImageVector.Builder(
            name = "ClubsUnknown",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 0.5f)
                horizontalLineToRelative(17f)
                moveTo(24f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(26f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 2.5f)
                horizontalLineToRelative(9f)
                moveTo(32f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(26f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 5.5f)
                horizontalLineToRelative(18f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(13f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(21f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(19f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(15f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(13f)
                moveTo(28f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 16.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 16.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(14f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(15f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(9f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(12f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 36.5f)
                horizontalLineToRelative(14f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(17f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(8f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 38.5f)
                horizontalLineToRelative(19f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 40.5f)
                horizontalLineToRelative(15f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(9f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 42.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(12f)
                moveTo(31f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(10f)
                moveTo(16f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(13f)
                moveTo(28f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(15f)
                moveTo(24f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(22f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(19f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(12f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 52.5f)
                horizontalLineToRelative(12f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(7f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(9f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(4f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _ClubsUnknown!!
    }

@Suppress("ObjectPropertyName")
private var _ClubsUnknown: ImageVector? = null
