package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Clubs5: ImageVector
    get() {
        if (_Clubs5 != null) {
            return _Clubs5!!
        }
        _Clubs5 = ImageVector.Builder(
            name = "Clubs5",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 53.5f)
                horizontalLineToRelative(14f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 1.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 1.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 2.5f)
                horizontalLineToRelative(22f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(11f)
                moveTo(23f, 3.5f)
                horizontalLineToRelative(9f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 4.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 5.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(12f)
                moveTo(20f, 7.5f)
                horizontalLineToRelative(9f)
                moveTo(31f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 10.5f)
                horizontalLineToRelative(24f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(12f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(12f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(24f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(10f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(14f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(10f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(10f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 40.5f)
                horizontalLineToRelative(27f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(17f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(19f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(34f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(15f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(10f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(10f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 52.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(10f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Clubs5!!
    }

@Suppress("ObjectPropertyName")
private var _Clubs5: ImageVector? = null
