package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Clubs10: ImageVector
    get() {
        if (_Clubs10 != null) {
            return _Clubs10!!
        }
        _Clubs10 = ImageVector.Builder(
            name = "Clubs10",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 0.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(13f)
                moveTo(16f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 2.5f)
                horizontalLineToRelative(11f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 3.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 4.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 5.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(11f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(11f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(12f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(15f)
                moveTo(33f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(12f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 46.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 50.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(12f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(9f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Clubs10!!
    }

@Suppress("ObjectPropertyName")
private var _Clubs10: ImageVector? = null
