package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Clubs4: ImageVector
    get() {
        if (_Clubs4 != null) {
            return _Clubs4!!
        }
        _Clubs4 = ImageVector.Builder(
            name = "Clubs4",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(14f)
                moveTo(18f, 0.5f)
                horizontalLineToRelative(12f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(30f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 1.5f)
                horizontalLineToRelative(15f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(29f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(9f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 5.5f)
                horizontalLineToRelative(11f)
                moveTo(27f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(13f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(12f)
                moveTo(25f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 11.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 12.5f)
                horizontalLineToRelative(25f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(18f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 14.5f)
                horizontalLineToRelative(11f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 14.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(12f)
                moveTo(18f, 16.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(21f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(16f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(26f)
                moveTo(2f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(20f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(14f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(14f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(12f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(15f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(17f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(11f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(34f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(6f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Clubs4!!
    }

@Suppress("ObjectPropertyName")
private var _Clubs4: ImageVector? = null
