package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Clubs7: ImageVector
    get() {
        if (_Clubs7 != null) {
            return _Clubs7!!
        }
        _Clubs7 = ImageVector.Builder(
            name = "Clubs7",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 0.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 53.5f)
                horizontalLineToRelative(12f)
                moveTo(27f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(19f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 7.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(11f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(13f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(9f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(13f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(15f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(23f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(17f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(12f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(11f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(25f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(25f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 52.5f)
                horizontalLineToRelative(24f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Clubs7!!
    }

@Suppress("ObjectPropertyName")
private var _Clubs7: ImageVector? = null
