package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Clubs3: ImageVector
    get() {
        if (_Clubs3 != null) {
            return _Clubs3!!
        }
        _Clubs3 = ImageVector.Builder(
            name = "Clubs3",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 0.5f)
                horizontalLineToRelative(17f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 53.5f)
                horizontalLineToRelative(13f)
                moveTo(19f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(18f)
                moveTo(23f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(14f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(12f)
                moveTo(18f, 3.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 3.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(11f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 5.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 7.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(10f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(21f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(12f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 13.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(22f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 16.5f)
                horizontalLineToRelative(11f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 18.5f)
                horizontalLineToRelative(10f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(12f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(15f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(20f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 36.5f)
                horizontalLineToRelative(8f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 37.5f)
                horizontalLineToRelative(21f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(21f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(12f)
                moveTo(3f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(11f)
                moveTo(23f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(32f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(12f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(18f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(13f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(12f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(12f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(12f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(13f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(23f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 52.5f)
                horizontalLineToRelative(23f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(32f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Clubs3!!
    }

@Suppress("ObjectPropertyName")
private var _Clubs3: ImageVector? = null
