package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Clubs9: ImageVector
    get() {
        if (_Clubs9 != null) {
            return _Clubs9!!
        }
        _Clubs9 = ImageVector.Builder(
            name = "Clubs9",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(21f)
                moveTo(32f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 1.5f)
                horizontalLineToRelative(13f)
                moveTo(19f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(32f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 4.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(17f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 7.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(22f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 41.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(26f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(10f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(10f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 10.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Clubs9!!
    }

@Suppress("ObjectPropertyName")
private var _Clubs9: ImageVector? = null
