package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ClubsAce: ImageVector
    get() {
        if (_ClubsAce != null) {
            return _ClubsAce!!
        }
        _ClubsAce = ImageVector.Builder(
            name = "ClubsAce",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(8f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 1.5f)
                horizontalLineToRelative(12f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(22f)
                moveTo(26f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 3.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 3.5f)
                horizontalLineToRelative(8f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(19f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(16f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 7.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(14f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(12f)
                moveTo(34f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 11.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(20f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(14f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(31f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(14f)
                moveTo(3f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(32f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(14f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(22f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(24f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(19f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(30f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(14f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 43.5f)
                horizontalLineToRelative(28f)
                moveTo(32f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(11f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 45.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(19f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 48.5f)
                horizontalLineToRelative(16f)
                moveTo(33f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(10f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _ClubsAce!!
    }

@Suppress("ObjectPropertyName")
private var _ClubsAce: ImageVector? = null
