package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ClubsKing: ImageVector
    get() {
        if (_ClubsKing != null) {
            return _ClubsKing!!
        }
        _ClubsKing = ImageVector.Builder(
            name = "ClubsKing",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(11f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 53.5f)
                horizontalLineToRelative(23f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 0.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(13f)
                moveTo(17f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(18f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(19f)
                moveTo(27f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(11f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(16f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(16f)
                moveTo(30f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(16f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(12f)
                moveTo(32f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(18f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(26f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(19f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(17f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(14f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(13f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(19f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(11f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(11f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 37.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 41.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(8f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCBBB35)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE2D245)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D245)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(11f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(12f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D244)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88038)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 41.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88138)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88039)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFC2605E)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFBA6926)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFBB6926)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 23.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCABB35)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D345)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 24.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFC2615E)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB96926)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 45.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE8D8BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D8BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD8C5A8)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D8BC)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD4B587)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAD8A56)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAC8A56)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAD8B56)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD4B586)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB86926)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD8C4A8)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD98038)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 40.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD4B487)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF332D52)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF645F86)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 47.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 48.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 50.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF645F87)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF322D52)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD8C5A9)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 46.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF645E86)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF332C52)),
                strokeLineWidth = 1f
            ) {
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF655F86)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD9C5A8)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 52.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _ClubsKing!!
    }

@Suppress("ObjectPropertyName")
private var _ClubsKing: ImageVector? = null
