package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Clubs8: ImageVector
    get() {
        if (_Clubs8 != null) {
            return _Clubs8!!
        }
        _Clubs8 = ImageVector.Builder(
            name = "Clubs8",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 0.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 53.5f)
                horizontalLineToRelative(15f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 2.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 2.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 4.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(25f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(11f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 30.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 52.5f)
                horizontalLineToRelative(26f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 44.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 47.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Clubs8!!
    }

@Suppress("ObjectPropertyName")
private var _Clubs8: ImageVector? = null
