package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Diamonds5: ImageVector
    get() {
        if (_Diamonds5 != null) {
            return _Diamonds5!!
        }
        _Diamonds5 = ImageVector.Builder(
            name = "Diamonds5",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(15f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 0.5f)
                horizontalLineToRelative(8f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(22f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 2.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(29f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(11f)
                moveTo(21f, 4.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(10f)
                moveTo(19f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 5.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(13f)
                moveTo(19f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 10.5f)
                horizontalLineToRelative(30f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(13f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(24f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(12f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(12f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(11f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 46.5f)
                horizontalLineToRelative(13f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(32f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(19f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(12f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 52.5f)
                horizontalLineToRelative(18f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(10f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 53.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Diamonds5!!
    }

@Suppress("ObjectPropertyName")
private var _Diamonds5: ImageVector? = null
