package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Diamonds4: ImageVector
    get() {
        if (_Diamonds4 != null) {
            return _Diamonds4!!
        }
        _Diamonds4 = ImageVector.Builder(
            name = "Diamonds4",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(21f)
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(30f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 0.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(26f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(27f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(11f)
                moveTo(22f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 6.5f)
                horizontalLineToRelative(22f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(12f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(16f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(14f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(13f)
                moveTo(31f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(22f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(19f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(16f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(16f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 41.5f)
                horizontalLineToRelative(25f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(26f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(25f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(9f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(19f)
                moveTo(21f, 47.5f)
                horizontalLineToRelative(8f)
                moveTo(30f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(23f)
                moveTo(25f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(23f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(12f)
                moveTo(17f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(9f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 31.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Diamonds4!!
    }

@Suppress("ObjectPropertyName")
private var _Diamonds4: ImageVector? = null
