package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Diamonds2: ImageVector
    get() {
        if (_Diamonds2 != null) {
            return _Diamonds2!!
        }
        _Diamonds2 = ImageVector.Builder(
            name = "Diamonds2",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 0.5f)
                horizontalLineToRelative(24f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(18f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 2.5f)
                horizontalLineToRelative(11f)
                moveTo(32f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(19f)
                moveTo(29f, 3.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(9f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 6.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(18f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(18f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(11f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(16f)
                moveTo(23f, 13.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(14f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(11f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(13f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(12f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(14f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(16f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(16f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(10f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(22f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(30f)
                moveTo(33f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(24f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(21f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(15f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(16f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(18f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(9f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(12f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(19f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(26f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 50.5f)
                horizontalLineToRelative(12f)
                moveTo(28f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 52.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 52.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(9f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Diamonds2!!
    }

@Suppress("ObjectPropertyName")
private var _Diamonds2: ImageVector? = null
