package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DiamondsUnknown: ImageVector
    get() {
        if (_DiamondsUnknown != null) {
            return _DiamondsUnknown!!
        }
        _DiamondsUnknown = ImageVector.Builder(
            name = "DiamondsUnknown",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(22f, 0.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(17f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 1.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(12f)
                moveTo(23f, 2.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 4.5f)
                horizontalLineToRelative(19f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 5.5f)
                horizontalLineToRelative(16f)
                moveTo(31f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(13f)
                moveTo(25f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(14f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(19f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(24f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(15f)
                moveTo(2f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 16.5f)
                horizontalLineToRelative(16f)
                moveTo(33f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(20f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(10f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 20.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(14f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(15f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(11f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(10f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(12f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(13f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(17f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(33f)
                moveTo(2f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 45.5f)
                horizontalLineToRelative(13f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 46.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(16f)
                moveTo(29f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(22f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(12f)
                moveTo(33f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 52.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 52.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(6f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _DiamondsUnknown!!
    }

@Suppress("ObjectPropertyName")
private var _DiamondsUnknown: ImageVector? = null
