package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Diamonds7: ImageVector
    get() {
        if (_Diamonds7 != null) {
            return _Diamonds7!!
        }
        _Diamonds7 = ImageVector.Builder(
            name = "Diamonds7",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 0.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 53.5f)
                horizontalLineToRelative(22f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 2.5f)
                horizontalLineToRelative(14f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 3.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(12f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(16f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(12f)
                moveTo(19f, 5.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(7f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(26f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(26f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(17f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(9f)
                moveTo(33f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(12f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(15f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(14f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(13f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 44.5f)
                horizontalLineToRelative(20f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(32f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(21f)
                moveTo(34f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(22f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(15f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(21f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(8f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Diamonds7!!
    }

@Suppress("ObjectPropertyName")
private var _Diamonds7: ImageVector? = null
