package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Diamonds3: ImageVector
    get() {
        if (_Diamonds3 != null) {
            return _Diamonds3!!
        }
        _Diamonds3 = ImageVector.Builder(
            name = "Diamonds3",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 1.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 2.5f)
                horizontalLineToRelative(17f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 3.5f)
                horizontalLineToRelative(20f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(23f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(18f)
                moveTo(25f, 6.5f)
                horizontalLineToRelative(10f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 9.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 10.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(16f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 14.5f)
                horizontalLineToRelative(21f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(10f)
                moveTo(18f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(11f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(24f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(33f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(14f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(16f)
                moveTo(34f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(17f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(19f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(18f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(28f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(14f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(23f)
                moveTo(2f, 44.5f)
                horizontalLineToRelative(33f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 45.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(13f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(17f)
                moveTo(26f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(34f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 51.5f)
                horizontalLineToRelative(13f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(21f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Diamonds3!!
    }

@Suppress("ObjectPropertyName")
private var _Diamonds3: ImageVector? = null
