package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Diamonds8: ImageVector
    get() {
        if (_Diamonds8 != null) {
            return _Diamonds8!!
        }
        _Diamonds8 = ImageVector.Builder(
            name = "Diamonds8",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(20f)
                moveTo(24f, 53.5f)
                horizontalLineToRelative(9f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(30f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(21f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(15f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(22f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(14f)
                moveTo(27f, 16.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(25f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(18f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(14f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 50.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(22f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(20f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Diamonds8!!
    }

@Suppress("ObjectPropertyName")
private var _Diamonds8: ImageVector? = null
