package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Diamonds6: ImageVector
    get() {
        if (_Diamonds6 != null) {
            return _Diamonds6!!
        }
        _Diamonds6 = ImageVector.Builder(
            name = "Diamonds6",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(12f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(11f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(16f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(31f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(19f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 3.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(12f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 7.5f)
                horizontalLineToRelative(15f)
                moveTo(32f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(10f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 10.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(18f)
                moveTo(30f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(9f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(11f)
                moveTo(33f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(12f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(13f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(3f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 41.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(19f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 46.5f)
                horizontalLineToRelative(8f)
                moveTo(28f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(11f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(26f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(11f)
                moveTo(19f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(16f)
                moveTo(21f, 52.5f)
                horizontalLineToRelative(12f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Diamonds6!!
    }

@Suppress("ObjectPropertyName")
private var _Diamonds6: ImageVector? = null
