package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DiamondsAce: ImageVector
    get() {
        if (_DiamondsAce != null) {
            return _DiamondsAce!!
        }
        _DiamondsAce = ImageVector.Builder(
            name = "DiamondsAce",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(13f)
                moveTo(17f, 0.5f)
                horizontalLineToRelative(10f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 53.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(10f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 1.5f)
                horizontalLineToRelative(10f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(12f)
                moveTo(15f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 2.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(21f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(12f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(18f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(20f)
                moveTo(27f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(21f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(17f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(22f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 10.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 12.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(20f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(14f)
                moveTo(29f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(10f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(19f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(23f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 39.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(28f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(12f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(14f)
                moveTo(34f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(18f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(12f)
                moveTo(33f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(22f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(19f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 52.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 26.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _DiamondsAce!!
    }

@Suppress("ObjectPropertyName")
private var _DiamondsAce: ImageVector? = null
