package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val HeartsUnknown: ImageVector
    get() {
        if (_HeartsUnknown != null) {
            return _HeartsUnknown!!
        }
        _HeartsUnknown = ImageVector.Builder(
            name = "HeartsUnknown",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 0.5f)
                horizontalLineToRelative(15f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(19f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(9f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 3.5f)
                horizontalLineToRelative(14f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(12f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 5.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(11f)
                moveTo(32f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 12.5f)
                horizontalLineToRelative(14f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(12f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(31f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(21f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(12f)
                moveTo(33f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(10f)
                moveTo(31f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(17f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 38.5f)
                horizontalLineToRelative(10f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(14f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(27f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(24f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(30f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(31f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(15f)
                moveTo(28f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(18f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 49.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(11f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(7f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(10f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(9f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _HeartsUnknown!!
    }

@Suppress("ObjectPropertyName")
private var _HeartsUnknown: ImageVector? = null
