package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val HeartsQueen: ImageVector
    get() {
        if (_HeartsQueen != null) {
            return _HeartsQueen!!
        }
        _HeartsQueen = ImageVector.Builder(
            name = "HeartsQueen",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(15f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(30f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(11f)
                moveTo(16f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(11f)
                moveTo(19f, 3.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 4.5f)
                horizontalLineToRelative(11f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(10f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(9f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(17f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 7.5f)
                horizontalLineToRelative(9f)
                moveTo(32f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(8f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(17f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(13f)
                moveTo(27f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(12f)
                moveTo(23f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(18f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 16.5f)
                horizontalLineToRelative(14f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 17.5f)
                horizontalLineToRelative(14f)
                moveTo(24f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(10f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(20f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(12f)
                moveTo(34f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 23.5f)
                horizontalLineToRelative(16f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 26.5f)
                horizontalLineToRelative(11f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 30.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(9f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(10f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(3f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(7f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D245)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(10f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCBBB35)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D244)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D345)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB96926)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB96826)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCABB35)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 26.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB86926)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88038)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 47.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88039)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D8BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D9BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D8BC)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88138)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAD8A56)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD4B587)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAC8A56)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE8D8BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB96927)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB6AC9C)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD8C5A8)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFC2605E)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF792321)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFC3605E)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCBC3B6)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFC2605F)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE5DFD5)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFC2615E)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF6C8A51)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF99B680)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD8C4A8)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF98B680)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 49.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _HeartsQueen!!
    }

@Suppress("ObjectPropertyName")
private var _HeartsQueen: ImageVector? = null
