package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hearts10: ImageVector
    get() {
        if (_Hearts10 != null) {
            return _Hearts10!!
        }
        _Hearts10 = ImageVector.Builder(
            name = "Hearts10",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 0.5f)
                horizontalLineToRelative(19f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(12f)
                moveTo(17f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 53.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 1.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 2.5f)
                horizontalLineToRelative(11f)
                moveTo(26f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 3.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 3.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(12f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 5.5f)
                horizontalLineToRelative(13f)
                moveTo(23f, 5.5f)
                horizontalLineToRelative(10f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(10f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(14f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 13.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(10f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 51.5f)
                horizontalLineToRelative(27f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 52.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 52.5f)
                horizontalLineToRelative(11f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Hearts10!!
    }

@Suppress("ObjectPropertyName")
private var _Hearts10: ImageVector? = null
