package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hearts6: ImageVector
    get() {
        if (_Hearts6 != null) {
            return _Hearts6!!
        }
        _Hearts6 = ImageVector.Builder(
            name = "Hearts6",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(14f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(14f)
                moveTo(18f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 53.5f)
                horizontalLineToRelative(9f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 0.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(18f)
                moveTo(22f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(3f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 2.5f)
                horizontalLineToRelative(10f)
                moveTo(22f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 3.5f)
                horizontalLineToRelative(13f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 4.5f)
                horizontalLineToRelative(18f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(28f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(21f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 8.5f)
                horizontalLineToRelative(12f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(17f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(11f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(17f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(13f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(12f)
                moveTo(34f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 14.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(10f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(14f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 37.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(26f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(19f)
                moveTo(29f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(15f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(27f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 51.5f)
                horizontalLineToRelative(20f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(4f, 52.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(9f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 40.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Hearts6!!
    }

@Suppress("ObjectPropertyName")
private var _Hearts6: ImageVector? = null
