package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hearts8: ImageVector
    get() {
        if (_Hearts8 != null) {
            return _Hearts8!!
        }
        _Hearts8 = ImageVector.Builder(
            name = "Hearts8",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(16f)
                moveTo(21f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 1.5f)
                horizontalLineToRelative(12f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(14f)
                moveTo(22f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 2.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(15f)
                moveTo(24f, 3.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(12f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(11f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(15f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(10f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(30f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(9f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(12f)
                moveTo(26f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(10f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(11f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(8f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(8f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Hearts8!!
    }

@Suppress("ObjectPropertyName")
private var _Hearts8: ImageVector? = null
