package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val HeartsAce: ImageVector
    get() {
        if (_HeartsAce != null) {
            return _HeartsAce!!
        }
        _HeartsAce = ImageVector.Builder(
            name = "HeartsAce",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 0.5f)
                horizontalLineToRelative(17f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 53.5f)
                horizontalLineToRelative(13f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(16f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 3.5f)
                horizontalLineToRelative(10f)
                moveTo(28f, 3.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(27f)
                moveTo(34f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(15f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(13f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(19f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(13f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(21f)
                moveTo(32f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(22f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(17f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(13f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 16.5f)
                horizontalLineToRelative(12f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(13f)
                moveTo(2f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(10f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(14f)
                moveTo(34f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(13f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(10f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(25f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(20f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(11f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 40.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(16f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(22f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(30f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(22f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(12f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 47.5f)
                horizontalLineToRelative(15f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(13f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(16f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(22f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(12f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(18f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(11f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _HeartsAce!!
    }

@Suppress("ObjectPropertyName")
private var _HeartsAce: ImageVector? = null
