package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hearts3: ImageVector
    get() {
        if (_Hearts3 != null) {
            return _Hearts3!!
        }
        _Hearts3 = ImageVector.Builder(
            name = "Hearts3",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 0.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 0.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(30f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 2.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 3.5f)
                horizontalLineToRelative(11f)
                moveTo(22f, 3.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(12f)
                moveTo(33f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(17f)
                moveTo(25f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 5.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(11f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(12f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(13f)
                moveTo(24f, 10.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(9f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(24f)
                moveTo(2f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 15.5f)
                horizontalLineToRelative(18f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(14f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(19f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 25.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(10f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(19f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 38.5f)
                horizontalLineToRelative(10f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(12f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(20f, 40.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(26f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(11f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(15f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(19f)
                moveTo(28f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(21f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(14f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(13f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 50.5f)
                horizontalLineToRelative(16f)
                moveTo(21f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(11f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(14f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 52.5f)
                horizontalLineToRelative(13f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Hearts3!!
    }

@Suppress("ObjectPropertyName")
private var _Hearts3: ImageVector? = null
