package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hearts2: ImageVector
    get() {
        if (_Hearts2 != null) {
            return _Hearts2!!
        }
        _Hearts2 = ImageVector.Builder(
            name = "Hearts2",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 0.5f)
                horizontalLineToRelative(14f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 53.5f)
                horizontalLineToRelative(13f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(13f)
                moveTo(17f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(20f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 4.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 4.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(10f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(17f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(14f)
                moveTo(21f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(32f)
                moveTo(34f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(13f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(22f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(10f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 16.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(18f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 18.5f)
                horizontalLineToRelative(16f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(11f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 23.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(10f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(17f)
                moveTo(34f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(12f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 37.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(17f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(17f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(15f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(15f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(22f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(19f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 46.5f)
                horizontalLineToRelative(14f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(25f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(13f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(10f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(10f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(12f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 53.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Hearts2!!
    }

@Suppress("ObjectPropertyName")
private var _Hearts2: ImageVector? = null
