package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hearts4: ImageVector
    get() {
        if (_Hearts4 != null) {
            return _Hearts4!!
        }
        _Hearts4 = ImageVector.Builder(
            name = "Hearts4",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 0.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(11f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 1.5f)
                horizontalLineToRelative(12f)
                moveTo(23f, 1.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(11f)
                moveTo(18f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(29f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(9f)
                moveTo(18f, 7.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(14f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(28f)
                moveTo(30f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(14f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 16.5f)
                horizontalLineToRelative(19f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(17f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(12f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(30f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(16f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(10f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(20f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(22f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(32f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 43.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(21f)
                moveTo(34f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(23f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(15f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 46.5f)
                horizontalLineToRelative(14f)
                moveTo(19f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(10f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(13f)
                moveTo(20f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(14f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(15f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(8f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Hearts4!!
    }

@Suppress("ObjectPropertyName")
private var _Hearts4: ImageVector? = null
