package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hearts9: ImageVector
    get() {
        if (_Hearts9 != null) {
            return _Hearts9!!
        }
        _Hearts9 = ImageVector.Builder(
            name = "Hearts9",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(27f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 53.5f)
                horizontalLineToRelative(9f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 1.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 1.5f)
                horizontalLineToRelative(23f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(27f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 3.5f)
                horizontalLineToRelative(13f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(24f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 5.5f)
                horizontalLineToRelative(21f)
                moveTo(31f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(25f)
                moveTo(32f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(20f)
                moveTo(26f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 7.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(7f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 23.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 27.5f)
                horizontalLineToRelative(11f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 28.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 30.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(27f, 36.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 49.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(13f)
                moveTo(26f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(18f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(12f)
                moveTo(24f, 52.5f)
                horizontalLineToRelative(8f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 34.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(10f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13C3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Hearts9!!
    }

@Suppress("ObjectPropertyName")
private var _Hearts9: ImageVector? = null
