package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val SpadesAce: ImageVector
    get() {
        if (_SpadesAce != null) {
            return _SpadesAce!!
        }
        _SpadesAce = ImageVector.Builder(
            name = "SpadesAce",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 53.5f)
                horizontalLineToRelative(19f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(16f)
                moveTo(20f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 2.5f)
                horizontalLineToRelative(15f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(15f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(10f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 5.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(10f)
                moveTo(28f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 7.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(19f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 9.5f)
                horizontalLineToRelative(30f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 10.5f)
                horizontalLineToRelative(10f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(8f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(20f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 12.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(15f)
                moveTo(30f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(22f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(22f)
                moveTo(29f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 16.5f)
                horizontalLineToRelative(14f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 16.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(10f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 18.5f)
                horizontalLineToRelative(13f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(31f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(12f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(9f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(19f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(32f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 35.5f)
                horizontalLineToRelative(19f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(8f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 36.5f)
                horizontalLineToRelative(14f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 38.5f)
                horizontalLineToRelative(19f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 40.5f)
                horizontalLineToRelative(23f)
                moveTo(34f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 41.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 41.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 42.5f)
                horizontalLineToRelative(11f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 44.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(12f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(20f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(10f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 47.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(24f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(11f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 51.5f)
                horizontalLineToRelative(8f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(10f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(13f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(25f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _SpadesAce!!
    }

@Suppress("ObjectPropertyName")
private var _SpadesAce: ImageVector? = null
