package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Spades6: ImageVector
    get() {
        if (_Spades6 != null) {
            return _Spades6!!
        }
        _Spades6 = ImageVector.Builder(
            name = "Spades6",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(17f)
                moveTo(21f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 53.5f)
                horizontalLineToRelative(8f)
                moveTo(16f, 53.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 53.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 1.5f)
                horizontalLineToRelative(20f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 2.5f)
                horizontalLineToRelative(27f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(19f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(23f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 5.5f)
                horizontalLineToRelative(11f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(9f)
                moveTo(16f, 6.5f)
                horizontalLineToRelative(19f)
                moveTo(2f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(18f)
                moveTo(24f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(14f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(29f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(13f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(10f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 11.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 12.5f)
                horizontalLineToRelative(10f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 13.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(32f, 15.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 16.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(13f)
                moveTo(16f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 28.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 36.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(8f)
                moveTo(21f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 41.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(22f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 42.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 42.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 42.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(13f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(34f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(17f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(29f)
                moveTo(31f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 48.5f)
                horizontalLineToRelative(15f)
                moveTo(32f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 49.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(24f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(28f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 52.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 17.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 23.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 37.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 37.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 40.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(14f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 36.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Spades6!!
    }

@Suppress("ObjectPropertyName")
private var _Spades6: ImageVector? = null
