package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Spades3: ImageVector
    get() {
        if (_Spades3 != null) {
            return _Spades3!!
        }
        _Spades3 = ImageVector.Builder(
            name = "Spades3",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(26f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 53.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 53.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 1.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(21f)
                moveTo(24f, 2.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(13f, 4.5f)
                horizontalLineToRelative(16f)
                moveTo(30f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 5.5f)
                horizontalLineToRelative(4f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 6.5f)
                horizontalLineToRelative(14f)
                moveTo(23f, 6.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(22f)
                moveTo(2f, 8.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 8.5f)
                horizontalLineToRelative(13f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(7f)
                moveTo(33f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(22f)
                moveTo(24f, 9.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(19f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(12f)
                moveTo(23f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(10f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(13f)
                moveTo(26f, 12.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(28f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(27f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(23f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 18.5f)
                horizontalLineToRelative(16f)
                moveTo(2f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(11f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(13f)
                moveTo(21f, 20.5f)
                horizontalLineToRelative(10f)
                moveTo(33f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(12f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(30f, 22.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(33f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(6f)
                moveTo(16f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(17f)
                moveTo(31f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(11f)
                moveTo(26f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(22f)
                moveTo(2f, 37.5f)
                horizontalLineToRelative(24f)
                moveTo(28f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(13f)
                moveTo(15f, 38.5f)
                horizontalLineToRelative(12f)
                moveTo(28f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(32f, 38.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(25f, 39.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(24f)
                moveTo(26f, 40.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(16f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(15f)
                moveTo(18f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 42.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(17f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 44.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 45.5f)
                horizontalLineToRelative(21f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(9f)
                moveTo(18f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(22f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 49.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(9f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(23f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 52.5f)
                horizontalLineToRelative(25f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 20.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 22.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(7f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 53.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Spades3!!
    }

@Suppress("ObjectPropertyName")
private var _Spades3: ImageVector? = null
