package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val SpadesQueen: ImageVector
    get() {
        if (_SpadesQueen != null) {
            return _SpadesQueen!!
        }
        _SpadesQueen = ImageVector.Builder(
            name = "SpadesQueen",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(7f, 0.5f)
                horizontalLineToRelative(14f)
                moveTo(22f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(18f)
                moveTo(23f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(6f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(16f)
                moveTo(20f, 1.5f)
                horizontalLineToRelative(13f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 2.5f)
                horizontalLineToRelative(15f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 3.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 4.5f)
                horizontalLineToRelative(16f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 5.5f)
                horizontalLineToRelative(20f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 6.5f)
                horizontalLineToRelative(19f)
                moveTo(33f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(17f)
                moveTo(28f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 8.5f)
                horizontalLineToRelative(22f)
                moveTo(32f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 9.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(23f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(23f, 10.5f)
                horizontalLineToRelative(12f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(16f)
                moveTo(29f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(20f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(7f, 13.5f)
                horizontalLineToRelative(28f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 15.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 15.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(22f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(26f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 18.5f)
                horizontalLineToRelative(6f)
                moveTo(10f, 18.5f)
                horizontalLineToRelative(15f)
                moveTo(26f, 18.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(16f)
                moveTo(23f, 20.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 21.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(15f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(17f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 23.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(14f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(9f)
                moveTo(23f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(23f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(24f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(11f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 32.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(8f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 34.5f)
                horizontalLineToRelative(9f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 36.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 37.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 37.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 38.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(6f)
                moveTo(2f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(8f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 40.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(11f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 42.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 47.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 48.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(31f, 50.5f)
                horizontalLineToRelative(4f)
                moveTo(4f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 52.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(29f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 44.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(3f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 5.5f)
                horizontalLineToRelative(5f)
                moveTo(32f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 6.5f)
                horizontalLineToRelative(7f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 8.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(8f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(31f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88038)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D245)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(6f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCBBB35)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 25.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE3D244)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF5F381E)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD88039)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 25.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCABB35)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 26.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE2D245)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF825231)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 47.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD8C5A8)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD8C5A9)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D8BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(21f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(4f)
                moveTo(21f, 35.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 37.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 38.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(17f, 42.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 48.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 52.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE8D8BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D8BC)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF825230)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF825331)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAD8A56)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 33.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 34.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD4B587)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 40.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAD8A57)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFAC8A56)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 33.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE9D9BD)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3A)),
                strokeLineWidth = 1f
            ) {
                moveTo(17f, 37.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA03D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 38.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFA13D3B)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 38.5f)
                horizontalLineToRelative(2f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB6AC9C)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 43.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF645F86)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(15f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(14f, 45.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 51.5f)
                horizontalLineToRelative(5f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 52.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 52.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB6AD9C)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFB6AC9D)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 42.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF332D52)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF645E86)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCBC3B6)),
                strokeLineWidth = 1f
            ) {
                moveTo(24f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF835231)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 44.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE5DFD5)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCBC3B7)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 44.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFCBC2B6)),
                strokeLineWidth = 1f
            ) {
                moveTo(25f, 44.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF5F391E)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFE5DED5)),
                strokeLineWidth = 1f
            ) {
                moveTo(22f, 46.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF645F87)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF6C8A51)),
                strokeLineWidth = 1f
            ) {
                moveTo(19f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 51.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF99B680)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 49.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(3f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF322D52)),
                strokeLineWidth = 1f
            ) {
                moveTo(27f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF655F86)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF332C52)),
                strokeLineWidth = 1f
            ) {
                moveTo(28f, 48.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFD4B586)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _SpadesQueen!!
    }

@Suppress("ObjectPropertyName")
private var _SpadesQueen: ImageVector? = null
