package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Spades2: ImageVector
    get() {
        if (_Spades2 != null) {
            return _Spades2!!
        }
        _Spades2 = ImageVector.Builder(
            name = "Spades2",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 0.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 0.5f)
                horizontalLineToRelative(4f)
                moveTo(28f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 53.5f)
                horizontalLineToRelative(21f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(12f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(20f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 1.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(11f, 2.5f)
                horizontalLineToRelative(6f)
                moveTo(18f, 2.5f)
                horizontalLineToRelative(8f)
                moveTo(27f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 3.5f)
                horizontalLineToRelative(23f)
                moveTo(29f, 3.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 4.5f)
                horizontalLineToRelative(10f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 4.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(15f)
                moveTo(21f, 5.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 6.5f)
                horizontalLineToRelative(8f)
                moveTo(14f, 6.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 7.5f)
                horizontalLineToRelative(18f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(10f)
                moveTo(19f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 8.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 8.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(8f)
                moveTo(19f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 9.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 10.5f)
                horizontalLineToRelative(18f)
                moveTo(30f, 10.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 11.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 11.5f)
                horizontalLineToRelative(16f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 12.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(27f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(8f)
                moveTo(17f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 16.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 16.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 17.5f)
                horizontalLineToRelative(15f)
                moveTo(31f, 17.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 18.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(20f, 19.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(10f)
                moveTo(16f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 21.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(10f)
                moveTo(29f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(8f)
                moveTo(18f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(23f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 23.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 24.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 25.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 25.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(10f)
                moveTo(16f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 27.5f)
                horizontalLineToRelative(3f)
                moveTo(31f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 28.5f)
                horizontalLineToRelative(11f)
                moveTo(27f, 28.5f)
                horizontalLineToRelative(8f)
                moveTo(2f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(8f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 30.5f)
                horizontalLineToRelative(10f)
                moveTo(34f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(19f)
                moveTo(25f, 31.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 32.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(13f)
                moveTo(28f, 33.5f)
                horizontalLineToRelative(7f)
                moveTo(2f, 34.5f)
                horizontalLineToRelative(7f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 34.5f)
                horizontalLineToRelative(17f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(8f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(15f, 35.5f)
                horizontalLineToRelative(19f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(16f)
                moveTo(18f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(31f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 37.5f)
                horizontalLineToRelative(7f)
                moveTo(15f, 37.5f)
                horizontalLineToRelative(20f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(12f)
                moveTo(14f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 38.5f)
                horizontalLineToRelative(16f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 39.5f)
                horizontalLineToRelative(16f)
                moveTo(24f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 40.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 40.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 41.5f)
                horizontalLineToRelative(30f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 42.5f)
                horizontalLineToRelative(9f)
                moveTo(13f, 42.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 42.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(26f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 44.5f)
                horizontalLineToRelative(19f)
                moveTo(27f, 44.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 44.5f)
                horizontalLineToRelative(5f)
                moveTo(2f, 45.5f)
                horizontalLineToRelative(18f)
                moveTo(21f, 45.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 45.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(8f)
                moveTo(10f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 46.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(27f, 46.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(8f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 47.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 47.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 48.5f)
                horizontalLineToRelative(7f)
                moveTo(14f, 48.5f)
                horizontalLineToRelative(15f)
                moveTo(30f, 48.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 49.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(18f)
                moveTo(28f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 50.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(32f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(13f)
                moveTo(19f, 52.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 52.5f)
                horizontalLineToRelative(10f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 50.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(18f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(10f, 21.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 23.5f)
                horizontalLineToRelative(7f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(11f, 26.5f)
                horizontalLineToRelative(5f)
                moveTo(19f, 26.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 27.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(7f)
                moveTo(26f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 31.5f)
                horizontalLineToRelative(4f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(5f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 27.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(15f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 31.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(13f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Spades2!!
    }

@Suppress("ObjectPropertyName")
private var _Spades2: ImageVector? = null
