package space.badluck.blackjack.VectorImages

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Spades5: ImageVector
    get() {
        if (_Spades5 != null) {
            return _Spades5!!
        }
        _Spades5 = ImageVector.Builder(
            name = "Spades5",
            defaultWidth = 36.dp,
            defaultHeight = 54.dp,
            viewportWidth = 36f,
            viewportHeight = 54f
        ).apply {
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 0.5f)
                horizontalLineToRelative(13f)
                moveTo(17f, 0.5f)
                horizontalLineToRelative(6f)
                moveTo(24f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 0.5f)
                horizontalLineToRelative(2f)
                moveTo(2f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 37.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 42.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 52.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 53.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 53.5f)
                horizontalLineToRelative(6f)
                moveTo(21f, 53.5f)
                horizontalLineToRelative(4f)
                moveTo(26f, 53.5f)
                horizontalLineToRelative(7f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000100)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF000001)),
                strokeLineWidth = 1f
            ) {
                moveTo(23f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 0.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(35f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 53.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFEFFFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(30f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(6f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 50.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color.White),
                strokeLineWidth = 1f
            ) {
                moveTo(4f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(12f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(17f, 1.5f)
                horizontalLineToRelative(7f)
                moveTo(25f, 1.5f)
                horizontalLineToRelative(4f)
                moveTo(30f, 1.5f)
                horizontalLineToRelative(3f)
                moveTo(2f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 2.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 2.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 2.5f)
                horizontalLineToRelative(14f)
                moveTo(1f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(16f, 3.5f)
                horizontalLineToRelative(14f)
                moveTo(31f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 3.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(7f, 4.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 4.5f)
                horizontalLineToRelative(5f)
                moveTo(16f, 4.5f)
                horizontalLineToRelative(7f)
                moveTo(24f, 4.5f)
                horizontalLineToRelative(11f)
                moveTo(1f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 5.5f)
                horizontalLineToRelative(14f)
                moveTo(20f, 5.5f)
                horizontalLineToRelative(9f)
                moveTo(30f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(33f, 5.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 6.5f)
                horizontalLineToRelative(3f)
                moveTo(10f, 6.5f)
                horizontalLineToRelative(7f)
                moveTo(18f, 6.5f)
                horizontalLineToRelative(6f)
                moveTo(25f, 6.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 6.5f)
                horizontalLineToRelative(4f)
                moveTo(1f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(5f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 7.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 7.5f)
                horizontalLineToRelative(12f)
                moveTo(23f, 7.5f)
                horizontalLineToRelative(12f)
                moveTo(1f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(9f, 8.5f)
                horizontalLineToRelative(21f)
                moveTo(32f, 8.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(9f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 9.5f)
                horizontalLineToRelative(11f)
                moveTo(28f, 9.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 10.5f)
                horizontalLineToRelative(15f)
                moveTo(17f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 10.5f)
                horizontalLineToRelative(8f)
                moveTo(31f, 10.5f)
                horizontalLineToRelative(2f)
                moveTo(34f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 11.5f)
                horizontalLineToRelative(11f)
                moveTo(15f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(21f, 11.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 11.5f)
                horizontalLineToRelative(5f)
                moveTo(31f, 11.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 12.5f)
                horizontalLineToRelative(5f)
                moveTo(9f, 12.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 12.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 12.5f)
                horizontalLineToRelative(15f)
                moveTo(34f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 13.5f)
                horizontalLineToRelative(10f)
                moveTo(16f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 13.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 13.5f)
                horizontalLineToRelative(4f)
                moveTo(29f, 13.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 13.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 14.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 14.5f)
                horizontalLineToRelative(2f)
                moveTo(19f, 14.5f)
                horizontalLineToRelative(4f)
                moveTo(24f, 14.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 14.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 15.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 15.5f)
                horizontalLineToRelative(7f)
                moveTo(16f, 15.5f)
                horizontalLineToRelative(5f)
                moveTo(24f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 15.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 16.5f)
                horizontalLineToRelative(6f)
                moveTo(11f, 16.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 16.5f)
                horizontalLineToRelative(10f)
                moveTo(25f, 16.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 17.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 17.5f)
                horizontalLineToRelative(9f)
                moveTo(26f, 17.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 18.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 18.5f)
                horizontalLineToRelative(3f)
                moveTo(17f, 18.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 18.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 19.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 19.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(28f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(31f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(33f, 19.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 20.5f)
                horizontalLineToRelative(4f)
                moveTo(15f, 20.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 21.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 21.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 21.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 22.5f)
                horizontalLineToRelative(6f)
                moveTo(9f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 22.5f)
                horizontalLineToRelative(3f)
                moveTo(18f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 22.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 23.5f)
                horizontalLineToRelative(4f)
                moveTo(11f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(19f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 23.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 23.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(13f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(1f, 25.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 25.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 25.5f)
                horizontalLineToRelative(6f)
                moveTo(34f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 26.5f)
                horizontalLineToRelative(3f)
                moveTo(5f, 26.5f)
                horizontalLineToRelative(8f)
                moveTo(22f, 26.5f)
                horizontalLineToRelative(4f)
                moveTo(27f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 26.5f)
                horizontalLineToRelative(6f)
                moveTo(1f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 27.5f)
                horizontalLineToRelative(4f)
                moveTo(9f, 27.5f)
                horizontalLineToRelative(2f)
                moveTo(12f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 27.5f)
                horizontalLineToRelative(13f)
                moveTo(1f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(16f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 28.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 28.5f)
                horizontalLineToRelative(9f)
                moveTo(1f, 29.5f)
                horizontalLineToRelative(8f)
                moveTo(12f, 29.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(26f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(32f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 30.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(20f, 30.5f)
                horizontalLineToRelative(2f)
                moveTo(27f, 30.5f)
                horizontalLineToRelative(8f)
                moveTo(1f, 31.5f)
                horizontalLineToRelative(6f)
                moveTo(14f, 31.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 31.5f)
                horizontalLineToRelative(5f)
                moveTo(28f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(15f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(18f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(29f, 32.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 33.5f)
                horizontalLineToRelative(5f)
                moveTo(29f, 33.5f)
                horizontalLineToRelative(4f)
                moveTo(34f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 34.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 34.5f)
                horizontalLineToRelative(6f)
                moveTo(23f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 34.5f)
                horizontalLineToRelative(5f)
                moveTo(34f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 35.5f)
                horizontalLineToRelative(9f)
                moveTo(11f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(19f, 35.5f)
                horizontalLineToRelative(5f)
                moveTo(25f, 35.5f)
                horizontalLineToRelative(6f)
                moveTo(32f, 35.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 36.5f)
                horizontalLineToRelative(7f)
                moveTo(13f, 36.5f)
                horizontalLineToRelative(9f)
                moveTo(27f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 36.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 37.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 38.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 38.5f)
                horizontalLineToRelative(5f)
                moveTo(12f, 38.5f)
                horizontalLineToRelative(7f)
                moveTo(20f, 38.5f)
                horizontalLineToRelative(15f)
                moveTo(2f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 39.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 39.5f)
                horizontalLineToRelative(12f)
                moveTo(27f, 39.5f)
                horizontalLineToRelative(2f)
                moveTo(30f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 39.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 40.5f)
                horizontalLineToRelative(14f)
                moveTo(16f, 40.5f)
                horizontalLineToRelative(3f)
                moveTo(20f, 40.5f)
                horizontalLineToRelative(7f)
                moveTo(28f, 40.5f)
                horizontalLineToRelative(7f)
                moveTo(1f, 41.5f)
                horizontalLineToRelative(19f)
                moveTo(21f, 41.5f)
                horizontalLineToRelative(6f)
                moveTo(28f, 41.5f)
                horizontalLineToRelative(3f)
                moveTo(33f, 41.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 42.5f)
                horizontalLineToRelative(34f)
                moveTo(1f, 43.5f)
                horizontalLineToRelative(3f)
                moveTo(6f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 43.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 43.5f)
                horizontalLineToRelative(4f)
                moveTo(19f, 43.5f)
                horizontalLineToRelative(14f)
                moveTo(34f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 44.5f)
                horizontalLineToRelative(21f)
                moveTo(23f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 44.5f)
                horizontalLineToRelative(10f)
                moveTo(1f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 45.5f)
                horizontalLineToRelative(4f)
                moveTo(12f, 45.5f)
                horizontalLineToRelative(21f)
                moveTo(34f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 46.5f)
                horizontalLineToRelative(18f)
                moveTo(20f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(26f, 46.5f)
                horizontalLineToRelative(5f)
                moveTo(33f, 46.5f)
                horizontalLineToRelative(2f)
                moveTo(1f, 47.5f)
                horizontalLineToRelative(4f)
                moveTo(6f, 47.5f)
                horizontalLineToRelative(25f)
                moveTo(32f, 47.5f)
                horizontalLineToRelative(3f)
                moveTo(1f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(4f, 48.5f)
                horizontalLineToRelative(13f)
                moveTo(18f, 48.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 48.5f)
                horizontalLineToRelative(3f)
                moveTo(25f, 48.5f)
                horizontalLineToRelative(8f)
                moveTo(34f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 49.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 49.5f)
                horizontalLineToRelative(2f)
                moveTo(14f, 49.5f)
                horizontalLineToRelative(21f)
                moveTo(1f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(13f, 50.5f)
                horizontalLineToRelative(11f)
                moveTo(25f, 50.5f)
                horizontalLineToRelative(10f)
                moveTo(2f, 51.5f)
                horizontalLineToRelative(7f)
                moveTo(10f, 51.5f)
                horizontalLineToRelative(3f)
                moveTo(14f, 51.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 51.5f)
                horizontalLineToRelative(10f)
                moveTo(28f, 51.5f)
                horizontalLineToRelative(6f)
                moveTo(3f, 52.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 52.5f)
                horizontalLineToRelative(27f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFFFE)),
                strokeLineWidth = 1f
            ) {
                moveTo(11f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 3.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(2f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 36.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(29f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(32f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 48.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 52.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFFFFFEFF)),
                strokeLineWidth = 1f
            ) {
                moveTo(16f, 1.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 2.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 9.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 11.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 12.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 13.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 14.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 15.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 17.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 26.5f)
                horizontalLineToRelative(1f)
                moveTo(34f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 38.5f)
                horizontalLineToRelative(1f)
                moveTo(1f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 39.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 40.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 41.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 43.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 44.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 45.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(25f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 46.5f)
                horizontalLineToRelative(1f)
                moveTo(31f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 49.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 51.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 51.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 3.5f)
                horizontalLineToRelative(3f)
                moveTo(3f, 4.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(5f, 6.5f)
                horizontalLineToRelative(1f)
                moveTo(4f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 16.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(23f, 17.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(11f, 18.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 18.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(11f, 19.5f)
                horizontalLineToRelative(3f)
                moveTo(21f, 19.5f)
                horizontalLineToRelative(7f)
                moveTo(6f, 20.5f)
                horizontalLineToRelative(9f)
                moveTo(20f, 20.5f)
                horizontalLineToRelative(6f)
                moveTo(27f, 20.5f)
                horizontalLineToRelative(2f)
                moveTo(6f, 21.5f)
                horizontalLineToRelative(9f)
                moveTo(21f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 21.5f)
                horizontalLineToRelative(3f)
                moveTo(28f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(7f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 22.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 23.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 24.5f)
                horizontalLineToRelative(3f)
                moveTo(12f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(15f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(18f, 24.5f)
                horizontalLineToRelative(2f)
                moveTo(22f, 24.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 25.5f)
                horizontalLineToRelative(5f)
                moveTo(13f, 26.5f)
                horizontalLineToRelative(9f)
                moveTo(14f, 27.5f)
                horizontalLineToRelative(5f)
                moveTo(20f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 28.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(9f, 29.5f)
                horizontalLineToRelative(2f)
                moveTo(17f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 29.5f)
                horizontalLineToRelative(3f)
                moveTo(8f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(15f, 30.5f)
                horizontalLineToRelative(4f)
                moveTo(22f, 30.5f)
                horizontalLineToRelative(5f)
                moveTo(7f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(21f, 31.5f)
                horizontalLineToRelative(7f)
                moveTo(6f, 32.5f)
                horizontalLineToRelative(2f)
                moveTo(9f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(20f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 32.5f)
                horizontalLineToRelative(6f)
                moveTo(6f, 33.5f)
                horizontalLineToRelative(8f)
                moveTo(20f, 33.5f)
                horizontalLineToRelative(9f)
                moveTo(7f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(10f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(21f, 34.5f)
                horizontalLineToRelative(2f)
                moveTo(24f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 34.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(24f, 35.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 36.5f)
                horizontalLineToRelative(5f)
                moveTo(22f, 36.5f)
                horizontalLineToRelative(5f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF010000)),
                strokeLineWidth = 1f
            ) {
                moveTo(0f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 8.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 10.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 28.5f)
                horizontalLineToRelative(1f)
                moveTo(0f, 47.5f)
                horizontalLineToRelative(1f)
                moveTo(12f, 53.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF46416B)),
                strokeLineWidth = 1f
            ) {
                moveTo(3f, 5.5f)
                horizontalLineToRelative(1f)
                moveTo(3f, 7.5f)
                horizontalLineToRelative(1f)
                moveTo(27f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 22.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(21f, 32.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47406B)),
                strokeLineWidth = 1f
            ) {
                moveTo(10f, 18.5f)
                horizontalLineToRelative(1f)
                moveTo(10f, 19.5f)
                horizontalLineToRelative(1f)
                moveTo(22f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(16f, 23.5f)
                horizontalLineToRelative(1f)
                moveTo(13f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 27.5f)
                horizontalLineToRelative(1f)
                moveTo(19f, 30.5f)
                horizontalLineToRelative(1f)
                moveTo(28f, 32.5f)
                horizontalLineToRelative(1f)
            }
            path(
                fill = SolidColor(Color.Black),
                stroke = SolidColor(Color(0xFF47416A)),
                strokeLineWidth = 1f
            ) {
                moveTo(26f, 20.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(23f, 21.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(17f, 24.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(20f, 25.5f)
                horizontalLineToRelative(1f)
                moveTo(11f, 29.5f)
                horizontalLineToRelative(1f)
                moveTo(8f, 32.5f)
                horizontalLineToRelative(1f)
                moveTo(14f, 33.5f)
                horizontalLineToRelative(1f)
                moveTo(26f, 34.5f)
                horizontalLineToRelative(1f)
            }
        }.build()

        return _Spades5!!
    }

@Suppress("ObjectPropertyName")
private var _Spades5: ImageVector? = null
